#*************  Makefile.ATMega128_demo_common  *****************
#            #######
#            ##  ##
#            #  ##    ####   #####    #####  ##  ##   #####
#              ##    ##  ##  ##  ##  ##      ##  ##  ##
#             ##  #  ######  ##  ##   ####   ##  ##   ####
#            ##  ##  ##      ##  ##      ##   #####      ##
#           #######   ####   ##  ##  #####       ##  #####
#                                            #####
#           Z-Wave, the wireless language.
#
#               Copyright (c) 2001
#               Zensys A/S
#               Denmark
#
#               All Rights Reserved
#
#     This source file is subject to the terms and conditions of the
#     Zensys Software License Agreement which restricts the manner
#     in which it may be used.
#
#---------------------------------------------------------------------------
#
#  Description: Common makefile for Atmel mega 128 demo appl.
#
#  Author:   Samer Seoud
#
#  Last Changed By:  $Author: sse $
#  Revision:         $Revision: 7382 $
#  Last Changed:     $Date: 2006-03-07 14:00:15 +0200 (Вв, 07 Бер 2006) $
#
#****************************************************************************

# Target name
TARGET:=BootLoader

all: $(TARGET).hex

include Makefile.common_atmel_compile_nolib

RELFILES=ZWaveFlash.r90\
	conhandle.r90\
	UART_buf_io.r90\
	lowlevel.r90



COMDEFINES:=-DMEGA128\
	-DENABLE_BIT_DEFINITIONS\
	-DnoENABLE_ERROR_HANDLER\
	-DDEBUG\
	-DBOOT_LOADER
	
CDEFINES+=
ADEFINES+=

include Makefile.common_atmel_link_nolib

